import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navebar from "./ui/navbar/Navbar";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import { Theme } from "@radix-ui/themes";
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <div><Navebar /></div>
          {children}
        </Theme>
      </body>
    </html>
  );
}
